stages:
  - build
  - test
  - docker_build
  - deploy

variables:
  IMAGE_PREFIX: "mamadouba634"
  DOCKER_CREDENTIALS: "docker-hub-credentials"

before_script:
  - echo "🚀 Initialisation du pipeline GitLab CI/CD"
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

build:
  stage: build
  script:
    - echo "📌 Compilation des services..."

test:
  stage: test
  script:
    - echo "📌 Exécution des tests unitaires..."
    - php artisan test

docker_build:
  stage: docker_build
  script:
    - echo "📌 Construction et push des images Docker"
    - for service in ms-classes ms-professeurs ms-emplois ms-cours ms-etudiants; do
        docker build -t $IMAGE_PREFIX/$service:latest devops/$service;
        docker push $IMAGE_PREFIX/$service:latest;
      done

deploy:
  stage: deploy
  script:
    - echo "📌 Déploiement des microservices..."
    - for service in ms-classes ms-professeurs ms-emplois ms-cours ms-etudiants; do
        docker run -d --name $service -p 8080:80 $IMAGE_PREFIX/$service:latest;
      done
